import logging
from typing import Optional

def run(url: Optional[str] = None, fetcher: Optional[callable] = None):
            if url is None and fetcher is None:
                raise SystemExit(
                    "Error: usa --url o --from-file "
                    "(o inyecta fetcher en tests)."
                )
            # rest of the function...
