name: Python CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -U pip
      - run: pip install ruff black pytest anyio httpx selectolax
      - run: ruff check .
      - run: black --check .
      - run: pytest -q
